version: '3.8'

services:
  mikey-ai:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: quantdesk-mikey-ai
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      # API Keys
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - COHERE_API_KEY=${COHERE_API_KEY}
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
      - XAI_API_KEY=${XAI_API_KEY}
      - QWEN_API_KEY=${QWEN_API_KEY}
      - HUGGINGFACE_API_KEY=${HUGGINGFACE_API_KEY}
      # Database (if using)
      - DATABASE_URL=${DATABASE_URL}
      # Solana
      - SOLANA_RPC_URL=${SOLANA_RPC_URL}
      - SOLANA_PRIVATE_KEY=${SOLANA_PRIVATE_KEY}
      # API Configuration
      - CORS_ORIGINS=${CORS_ORIGINS:-http://localhost:3001,http://localhost:5173}
      - RATE_LIMIT_WINDOW=${RATE_LIMIT_WINDOW:-900000}
      - RATE_LIMIT_MAX=${RATE_LIMIT_MAX:-100}
      # WebSocket
      - WS_PORT=3000
      - WS_HEARTBEAT_INTERVAL=30000
      - WS_MAX_CONNECTIONS=1000
      # Monitoring
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - SENTRY_DSN=${SENTRY_DSN}
      - PROMETHEUS_PORT=${PROMETHEUS_PORT:-9090}
    volumes:
      - ./logs:/app/logs
    networks:
      - quantdesk-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  quantdesk-network:
    external: true

