[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false
init-if-needed = true

[programs.localnet]
quantdesk_perp_dex = "C2T3UnvGdHwEkspXJG7JyAhwo6VKQEKjN6eCq69guYSw"

[programs.devnet]
quantdesk_perp_dex = "C2T3UnvGdHwEkspXJG7JyAhwo6VKQEKjN6eCq69guYSw"

[programs.testnet]
quantdesk_perp_dex = "C2T3UnvGdHwEkspXJG7JyAhwo6VKQEKjN6eCq69guYSw"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/keys/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
