version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: quantdesk-postgres
    environment:
      POSTGRES_DB: quantdesk
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: quantdesk-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend API
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: quantdesk-backend
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - PORT=3002
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/quantdesk
      - REDIS_URL=redis://redis:6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/node_modules
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: quantdesk-frontend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - VITE_API_URL=http://localhost:3002
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

  # Admin Dashboard
  admin:
    build:
      context: .
      dockerfile: Dockerfile.admin
    container_name: quantdesk-admin
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - VITE_API_URL=http://localhost:3002
    depends_on:
      - backend
    volumes:
      - ./admin-dashboard:/app
      - /app/node_modules

  # Data Ingestion Service
  data-ingestion:
    build:
      context: .
      dockerfile: Dockerfile.data-ingestion
    container_name: quantdesk-data-ingestion
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/quantdesk
      - REDIS_URL=redis://redis:6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./data-ingestion:/app
      - /app/node_modules

volumes:
  postgres_data:
  redis_data:

networks:
  default:
    name: quantdesk-network
